package tipo;

public class TipoAgrupamiento {
	
	String[] tiposAgrupamiento = {"TIPO_CLIENTE", "TIPO_DOCUMENTO", 
			"EXTRACT(DAY FROM CLIENTES.FECHA_CREACION), EXTRACT(MONTH FROM CLIENTES.FECHA_CREACION), EXTRACT(YEAR FROM CLIENTES.FECHA_CREACION)",
			"EXTRACT(MONTH FROM CLIENTES.FECHA_CREACION), EXTRACT(YEAR FROM CLIENTES.FECHA_CREACION)",
			"EXTRACT(YEAR FROM CLIENTES.FECHA_CREACION)"};
	
}
