package tipo;

public class TipoAgrupamiento {
	
	public final static String[] TIPOS_AGRUPAMIENTOS = {"TIPO_CLIENTE", "TIPO_DOCUMENTO", 
			"EXTRACT(DAY FROM FECHA_CREACION) || '/' || EXTRACT(MONTH FROM FECHA_CREACION) || '/' || EXTRACT(YEAR FROM FECHA_CREACION )",
			"EXTRACT(MONTH FROM FECHA_CREACION) || '/' || EXTRACT(YEAR FROM FECHA_CREACION )",
			"EXTRACT(YEAR FROM FECHA_CREACION)"};
	
}
