UNDEFINE idAlojamiento;
UNDEFINE fechaCotaInferior;
UNDEFINE fechaCotaSuperior;

DEFINE idAlojamiento;
DEFINE fechaCotaInferior;
DEFINE fechaCotaSuperior ;

SELECT *
FROM CLIENTES INNER JOIN RESERVAS ON RESERVAS.ID_CLIENTE =  CLIENTES.CARNET_UNIANDES 
            INNER JOIN OFERTAS_ALOJAMIENTOS ON RESERVAS.ID_AL_OF = OFERTAS_ALOJAMIENTOS.ID_AL
WHERE OFERTAS_ALOJAMIENTOS.ID_AL = $$idAl AND &&fechaCotaInferior <= RESERVAS.FECHA_INICIO AND RESERVAS.FECHA_FIN <= &&fechaCotaSuperior ;

//FALTAN GROUP BY Y ESAS MIERDAS QUE PIDEN.